service:
  name: gov-hdmf

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  profile: devalex
  stage: dev
  region: eu-west-1

functions:
  calculate-deduction:
    handler: handler.calculate
    events:
      - http:
          method: post
          path: api/v1/calculate
          request:
            template:
              application/json: '{ "salary" : "$input.params(''result_count'')" }'

custom:
  serverless-offline:
    port: 3002